#!/usr/bin/expect -f
#
# Overly Attached SSH
#
# Ask for password once and then re-connect and run initial command
# when disconnected.
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set timeout 30

set target [lrange $argv 0 1]
#set target "$argv1 [lrange $argv 0 2]\n"

send_user "Overly attached password:\ "
stty -echo
expect_user -re "(.*)\n"
set pw "$expect_out(1,string)"
stty echo
send_user "\n"

send_user "Immediate command:\ "
expect_user -re "(.*)\n"
set immediate "$expect_out(1,string)"

proc oassh {target pw immediate} {
    spawn "ssh" $target
    while {1} {
        expect {
            "Password:" {
                send "$pw\r"
            }
            "Last login" {
                send "$immediate\r"
                interact
                return
            }
            "Permission denied" {
                send_user "Wrong password\n"
                exit 1
            }
            -re "(Password: |Permission denied)" {
                send_user "Wrong password\n"
                exit 1
            }
        }
    }
}

for {} 1 {} {
    if [catch {oassh "$target" "$pw" "$immediate"} result] {
        puts stderr "Warning: $result"
        sleep 1
    }
    wait -i -1
}
